[tool.poetry]
name = "vbnigmm"
version = "2.1.0"
description = "Variational Bayes algorithm for normal inverse Gaussian mixture models"
license = "GPL-3.0-only"
authors = ["TAKEKAWA Takashi <takekawa@tk2lab.org>"]
readme = 'README.rst'
repository = "https://github.com/tk2lab/vbnigmm"
keywords = ["clustering"]

[tool.poetry.dependencies]
python = "^3.7 || ^3.8 || ^3.9"
numpy = "^1.19"
scipy = "^1.5"
scikit-learn = "^0.24"
tqdm = "^4.55"
tensorflow = "^2.4"
tensorflow_probability = "^0.12"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
